export interface SkillInterface {
  key: string;
  name: string;
  size: 1 | 2 | 3 | 4 | 5;
}

export const hardSkills: SkillInterface[] = [
  /* Front-End */
  { key: "html", name: "HTML5", size: 5 },
  { key: "css", name: "CSS3", size: 5 },
  { key: "js", name: "JavaScript", size: 5 },
  { key: "react", name: "React", size: 4 },
  { key: "next", name: "Next.js", size: 3 },
  { key: "tailwind", name: "Tailwind CSS", size: 4 },
  { key: "vue", name: "Vue.js", size: 1 },
  { key: "nuxt", name: "Nuxt.js", size: 1 },
  { key: "angular", name: "Angular", size: 1 },
  { key: "responsive-design", name: "Responsive Design", size: 4 },
  { key: "seo", name: "SEO", size: 3 },
  { key: "ssr", name: "SSR", size: 2 },
  { key: "sass", name: "Sass", size: 4 },
  { key: "semantical-html", name: "Semantical HTML", size: 4 },
  { key: "ts", name: "TypeScript", size: 4 },
  { key: "webpack", name: "Webpack", size: 1 },
  { key: "redux", name: "Redux", size: 1 },
  { key: "jquery", name: "jQuery", size: 1 },
  { key: "acessibility", name: "Web Accessibility", size: 3 },
  { key: "web-vitals", name: "Core Web Vitals", size: 4 },
  { key: "performance", name: "Web Performance", size: 2 },
  { key: "security", name: "Web Security", size: 2 },
  { key: "web-sockets", name: "Web Sockets", size: 1 },
  { key: "styled-components", name: "Styled Components", size: 1 },
  { key: "pwa", name: "PWA", size: 2 },
  /* Back-End */
  { key: "node", name: "Node.js", size: 3 },
  { key: "express", name: "Express", size: 3 },
  { key: "loopback", name: "LoopBack", size: 1 },
  { key: "meteor", name: "Meteor", size: 1 },
  /* Test  */
  { key: "jest", name: "Jest", size: 3 },
  { key: "coverage", name: "Code Coverage", size: 3 },
  { key: "react-testing-library", name: "React Testing Library", size: 3 },
  { key: "cypress", name: "Cypress", size: 2 },
  { key: "chromatic", name: "Chromatic", size: 1 },
  /* APIs */
  { key: "http", name: "HTTP", size: 3 },
  { key: "graphql", name: "GraphQL", size: 1 },
  { key: "rest", name: "REST", size: 1 },
  /* PHP */
  { key: "php", name: "PHP", size: 1 },
  { key: "wordpress", name: "WordPress", size: 1 },
  { key: "magento", name: "Magento", size: 1 },
  { key: "laravel", name: "Laravel", size: 1 },
  /* Web Servers */
  { key: "nginx", name: "Nginx", size: 3 },
  { key: "apache", name: "Apache", size: 2 },
  /* CI / CD */
  { key: "github-actions", name: "GitHub Actions", size: 2 },
  { key: "bash", name: "Bash", size: 1 },
  { key: "docker", name: "Docker", size: 1 },
  { key: "yml", name: "YML", size: 1 },
  { key: "aws", name: "AWS", size: 2 },
  { key: "k8s", name: "Kubernets", size: 1 },
  { key: "terraform", name: "Terraform", size: 1 },
  /* Database */
  { key: "sql", name: "SQL", size: 3 },
  { key: "mysql", name: "MySQL", size: 1 },
  { key: "sql-server", name: "SQL Server", size: 1 },
  { key: "postgre", name: "PostgreSQL", size: 1 },
  { key: "oracle", name: "Oracle", size: 1 },
  { key: "nosql", name: "NoSQL", size: 2 },
  { key: "mongo", name: "MongoDB", size: 1 },
  /* Management Tools */
  { key: "jira", name: "Jira", size: 1 },
  { key: "confluence", name: "Confluence", size: 1 },
  { key: "slack-workflos", name: "Slack Workflows", size: 1 },
  { key: "slack-apps", name: "Slack Apps", size: 1 },
  { key: "bpmn", name: "BPMN", size: 1 },
  /* Business */
  { key: "a_b-testing", name: "A/B Testing", size: 1 },
  { key: "atomic-design", name: "Atomic Design", size: 1 },
  { key: "design-systems", name: "Design Systems", size: 1 },
  { key: "semver", name: "Semantic Versioning", size: 1 },
  { key: "ui_ux", name: "UI/UX", size: 1 },
  /* Other */
  { key: "functional-programming", name: "Functional Programming", size: 1 },
  { key: "oop", name: "OOP", size: 1 },
  { key: "regex", name: "Regular Expressions", size: 2 },
  { key: "markdown", name: "MarkDown", size: 1 },
];

export const softSkills = [
  { key: "communication", size: 5 },
  { key: "leadership", size: 5 },
  { key: "problem-solving", size: 5 },
  { key: "decision-making", size: 5 },
  { key: "empathy", size: 5 },
  { key: "conflict-resolution", size: 4 },
  { key: "adaptability", size: 4 },
  { key: "time-management", size: 3 },
  { key: "organization", size: 3 },
  { key: "strategic-thinking", size: 3 },
  { key: "mentoring", size: 4 },
  { key: "negotiation", size: 4 },
  { key: "resilience", size: 5 },
  { key: "critical-thinking", size: 3 },
  { key: "creativity", size: 3 },
  { key: "active-listening", size: 3 },
  { key: "team-building", size: 2 },
  { key: "ethical-decision-making", size: 1 },
  { key: "customer-orientation", size: 3 },
  { key: "learning-agility", size: 3 },
  { key: "curiosity", size: 4 },
  { key: "patience", size: 1 },
  { key: "public-speaking", size: 1 },
  { key: "networking", size: 1 },
  { key: "multitasking", size: 1 },
  { key: "attention-to-detail", size: 1 },
  { key: "motivation", size: 1 },
  { key: "persuasion", size: 1 },
  { key: "emotional-intelligence", size: 1 },
] as const;
