export interface SkillInterface {
  name: string;
  size: 1 | 2 | 3 | 4 | 5;
}

export const hardSkills: SkillInterface[] = [
  /* Front-End */
  { name: "HTML5", size: 5 },
  { name: "CSS3", size: 5 },
  { name: "JavaScript", size: 5 },
  { name: "React", size: 4 },
  { name: "Next.js", size: 3 },
  { name: "Tailwind CSS", size: 4 },
  { name: "Vue.js", size: 1 },
  { name: "Nuxt.js", size: 1 },
  { name: "Angular", size: 1 },
  { name: "Responsive Design", size: 4 },
  { name: "SEO", size: 3 },
  { name: "SSR", size: 2 },
  { name: "Sass", size: 4 },
  { name: "Semantical HTML", size: 4 },
  { name: "TypeScript", size: 4 },
  { name: "Webpack", size: 1 },
  { name: "Redux", size: 1 },
  { name: "jQuery", size: 1 },
  { name: "Web Accessibility", size: 3 },
  { name: "Core Web Vitals", size: 4 },
  { name: "Web Performance", size: 2 },
  { name: "Web Security", size: 2 },
  { name: "Web Sockets", size: 1 },
  { name: "Styled Components", size: 1 },
  { name: "PWA", size: 2 },
  /* Back-End */
  { name: "Node.js", size: 3 },
  { name: "Express", size: 3 },
  { name: "LoopBack", size: 1 },
  { name: "Meteor", size: 1 },
  /* Test  */
  { name: "Jest", size: 3 },
  { name: "Code Coverage", size: 3 },
  { name: "React Testing Library", size: 3 },
  { name: "Cypress", size: 2 },
  { name: "Chromatic", size: 1 },
  /* APIs */
  { name: "HTTP", size: 3 },
  { name: "GraphQL", size: 1 },
  { name: "REST", size: 1 },
  /* PHP */
  { name: "PHP", size: 1 },
  { name: "WordPress", size: 1 },
  { name: "Magento", size: 1 },
  { name: "Laravel", size: 1 },
  /* Web Servers */
  { name: "Nginx", size: 3 },
  { name: "Apache", size: 2 },
  /* CI / CD */
  { name: "GitHub Actions", size: 2 },
  { name: "Bash", size: 1 },
  { name: "Docker", size: 1 },
  { name: "YML", size: 1 },
  { name: "AWS", size: 2 },
  { name: "Kubernets", size: 1 },
  { name: "Terraform", size: 1 },
  /* Database */
  { name: "SQL", size: 3 },
  { name: "MySQL", size: 1 },
  { name: "SQL Server", size: 1 },
  { name: "PostgreSQL", size: 1 },
  { name: "Oracle", size: 1 },
  { name: "NoSQL", size: 2 },
  { name: "MongoDB", size: 1 },
  /* Management Tools */
  { name: "Jira", size: 1 },
  { name: "Confluence", size: 1 },
  { name: "Slack Workflows", size: 1 },
  { name: "Slack Apps", size: 1 },
  { name: "BPMN", size: 1 },
  /* Business */
  { name: "A/B Testing", size: 1 },
  { name: "Atomic Design", size: 1 },
  { name: "Design Systems", size: 1 },
  { name: "Semantic Versioning", size: 1 },
  { name: "UI/UX", size: 1 },
  /* Other */
  { name: "Functional Programming", size: 1 },
  { name: "OOP", size: 1 },
  { name: "Regular Expressions", size: 2 },
  { name: "MarkDown", size: 1 },
];

export const softSkills = [
  { key: "communication", size: 5 },
  { key: "leadership", size: 5 },
  { key: "problem-solving", size: 5 },
  { key: "decision-making", size: 5 },
  { key: "empathy", size: 5 },
  { key: "conflict-resolution", size: 4 },
  { key: "adaptability", size: 4 },
  { key: "time-management", size: 3 },
  { key: "organization", size: 3 },
  { key: "strategic-thinking", size: 3 },
  { key: "mentoring", size: 4 },
  { key: "negotiation", size: 4 },
  { key: "resilience", size: 5 },
  { key: "critical-thinking", size: 3 },
  { key: "creativity", size: 3 },
  { key: "active-listening", size: 3 },
  { key: "team-building", size: 2 },
  { key: "ethical-decision-making", size: 1 },
  { key: "customer-orientation", size: 3 },
  { key: "learning-agility", size: 3 },
  { key: "curiosity", size: 4 },
  { key: "patience", size: 1 },
  { key: "public-speaking", size: 1 },
  { key: "networking", size: 1 },
  { key: "multitasking", size: 1 },
  { key: "attention-to-detail", size: 1 },
  { key: "motivation", size: 1 },
  { key: "persuasion", size: 1 },
  { key: "emotional-intelligence", size: 1 },
] as const;
