export interface ExperienceInterface {
  key: string;
  companyId: string;
  companyName: string;
  startDate: string;
  endDate: string | null;
  mainStack: string[];
  resume: boolean;
  resumeAccomplishments: number[];
  hasBlackLogo: boolean;
  hidden: boolean;
}

export const experience: ExperienceInterface[] = [
  {
    key: "lovevery-1",
    companyId: "lovevery",
    companyName: "Lovevery",
    startDate: "07-2024",
    endDate: null,
    mainStack: [
      "react",
      "next",
      "tailwind",
      "ts",
      "jest",
      "react-testing-library",
      "cypress",
      "playwright",
      "contentful",
      "stripe",
      "vercel",
    ],
    resume: true,
    resumeAccomplishments: [1, 2, 3],
    hasBlackLogo: false,
    hidden: false,
  },
  {
    key: "yestechnology-1",
    companyId: "yestechnology",
    companyName: "YES Technology",
    startDate: "08-2024",
    endDate: "09-2025",
    mainStack: [
      "react",
      "ts",
      "styled-components",
      "micro-frontend",
      "jest",
      "react-testing-library",
      "docker",
      "storybook",
    ],
    resume: false,
    resumeAccomplishments: [],
    hasBlackLogo: true,
    hidden: true,
  },
  {
    key: "pdsacademy-1",
    companyId: "pdsacademy",
    companyName: "PDSAcademy",
    startDate: "06-2025",
    endDate: "06-2025",
    mainStack: [
      "react",
      "next",
      "tailwind",
      "html",
      "css",
      "js",
      "functional-programming",
    ],
    resume: true,
    resumeAccomplishments: [1, 2],
    hasBlackLogo: true,
    hidden: true,
  },
  {
    key: "danielxavier-1",
    companyId: "danielxavier",
    companyName: "<DanielXavier />",
    startDate: "05-2024",
    endDate: "06-2024",
    mainStack: [
      "next",
      "ts",
      "tailwind",
      "jest",
      "react-testing-library",
      "cypress",
      "vercel",
      "node",
      "kong",
      "mysql",
    ],
    resume: true,
    resumeAccomplishments: [2, 3],
    hasBlackLogo: true,
    hidden: false,
  },
  {
    key: "olx-1",
    companyId: "olx",
    companyName: "OLX",
    startDate: "08-2021",
    endDate: "04-2024",
    mainStack: [
      "node",
      "rn",
      "postgre",
      "python",
      "es",
      "react",
      "storybook",
      "html",
      "css",
      "js",
      "s3",
      "firebase",
      "android",
      "java",
      "kotlin",
      "ios",
      "swift-ui",
      "ad-manager",
      "aws",
    ],
    resume: true,
    resumeAccomplishments: [1, 2, 3, 4],
    hasBlackLogo: false,
    hidden: false,
  },
  {
    key: "meaning-1",
    companyId: "meaning",
    companyName: "Meaning",
    startDate: "03-2022",
    endDate: "05-2023",
    mainStack: ["html", "css", "js", "bpmn", "gcp"],
    resume: true,
    resumeAccomplishments: [1, 2, 3],
    hasBlackLogo: false,
    hidden: false,
  },
  {
    key: "softplan-3",
    companyId: "softplan",
    companyName: "Softplan",
    startDate: "10-2020",
    endDate: "07-2021",
    mainStack: [
      "react",
      "micro-frontend",
      "dotnet",
      "graphql",
      "delphi",
      "sql-server",
      "aws",
    ],
    resume: true,
    resumeAccomplishments: [1, 2, 3],
    hasBlackLogo: false,
    hidden: false,
  },
  {
    key: "softplan-2",
    companyId: "softplan",
    companyName: "Softplan",
    startDate: "09-2019",
    endDate: "10-2020",
    mainStack: [
      "react",
      "micro-frontend",
      "dotnet",
      "graphql",
      "sql-server",
      "aws",
    ],
    resume: true,
    resumeAccomplishments: [1, 2, 4],
    hasBlackLogo: false,
    hidden: false,
  },
  {
    key: "softplan-1",
    companyId: "softplan",
    companyName: "Softplan",
    startDate: "12-2018",
    endDate: "08-2019",
    mainStack: [
      "react",
      "micro-frontend",
      "dotnet",
      "graphql",
      "sql-server",
      "aws",
    ],
    resume: true,
    resumeAccomplishments: [1, 2, 3],
    hasBlackLogo: false,
    hidden: false,
  },
  {
    key: "hotmart-3",
    companyId: "hotmart",
    companyName: "Hotmart",
    startDate: "06-2018",
    endDate: "11-2018",
    mainStack: [
      "vue",
      "nuxt",
      "node",
      "express",
      "mysql",
      "html",
      "css",
      "js",
      "aws",
    ],
    resume: true,
    resumeAccomplishments: [1, 2],
    hasBlackLogo: false,
    hidden: false,
  },
  {
    key: "hotmart-2",
    companyId: "hotmart",
    companyName: "Hotmart",
    startDate: "06-2017",
    endDate: "05-2018",
    mainStack: [
      "vue",
      "nuxt",
      "node",
      "express",
      "mysql",
      "html",
      "css",
      "js",
      "php",
      "wordpress",
      "nginx",
      "aws",
    ],
    resume: true,
    resumeAccomplishments: [1, 2],
    hasBlackLogo: false,
    hidden: false,
  },
  {
    key: "hotmart-1",
    companyId: "hotmart",
    companyName: "Hotmart",
    startDate: "12-2016",
    endDate: "05-2017",
    mainStack: [
      "html",
      "css",
      "js",
      "php",
      "wordpress",
      "nginx",
      "mysql",
      "aws",
    ],
    resume: true,
    resumeAccomplishments: [1],
    hasBlackLogo: false,
    hidden: false,
  },
  {
    key: "sydle-2",
    companyId: "sydle",
    companyName: "Sydle",
    startDate: "04-2014",
    endDate: "11-2016",
    mainStack: [
      "node",
      "express",
      "angular",
      "php",
      "wordpress",
      "magento",
      "mysql",
      "bpmn",
    ],
    resume: true,
    resumeAccomplishments: [1, 2, 3],
    hasBlackLogo: true,
    hidden: false,
  },
  {
    key: "sydle-1",
    companyId: "sydle",
    companyName: "Sydle",
    startDate: "04-2012",
    endDate: "03-2014",
    mainStack: ["js", "apache", "linux", "windows", "aws"],
    resume: true,
    resumeAccomplishments: [1, 2],
    hasBlackLogo: true,
    hidden: false,
  },
];
