export const experience = [
  {
    key: "danielxavier-1",
    companyId: "danielxavier",
    companyName: "<DanielXavier />",
    year: "2024",
    resume: true,
    resumeAccomplishments: [1, 2, 3],
    hasBlackLogo: true,
  },
  {
    key: "olx-4",
    companyId: "olx",
    companyName: "OLX",
    year: "2024",
    resume: true,
    resumeAccomplishments: [1, 2, 4],
    hasBlackLogo: false,
  },
  {
    key: "olx-3",
    companyId: "olx",
    companyName: "OLX",
    year: "2023",
    resume: true,
    resumeAccomplishments: [1, 2, 3, 4],
    hasBlackLogo: false,
  },
  {
    key: "olx-2",
    companyId: "olx",
    companyName: "OLX",
    year: "2022 ~ 2023",
    resume: true,
    resumeAccomplishments: [1, 3, 5],
    hasBlackLogo: false,
  },
  {
    key: "olx-1",
    companyId: "olx",
    companyName: "OLX",
    year: "2021 ~ 2022",
    resumeAccomplishments: [1, 2, 3],
    resume: true,
    hasBlackLogo: false,
  },
  {
    key: "meaning-1",
    companyId: "meaning",
    companyName: "Meaning",
    year: "2023",
    resumeAccomplishments: [1, 2, 3],
    resume: true,
    hasBlackLogo: false,
  },
  {
    key: "softplan-3",
    companyId: "softplan",
    companyName: "Softplan",
    year: "2020 ~ 2021",
    resume: true,
    resumeAccomplishments: [1, 2, 3],
    hasBlackLogo: false,
  },
  {
    key: "softplan-2",
    companyId: "softplan",
    companyName: "Softplan",
    year: "2019 ~ 2020",
    resume: true,
    resumeAccomplishments: [1, 2, 4],
    hasBlackLogo: false,
  },
  {
    key: "softplan-1",
    companyId: "softplan",
    companyName: "Softplan",
    year: "2018 ~ 2019",
    resume: true,
    resumeAccomplishments: [1, 2, 3],
    hasBlackLogo: false,
  },
  {
    key: "hotmart-3",
    companyId: "hotmart",
    companyName: "Hotmart",
    year: "2018",
    resume: true,
    resumeAccomplishments: [1, 2],
    hasBlackLogo: false,
  },
  {
    key: "hotmart-2",
    companyId: "hotmart",
    companyName: "Hotmart",
    year: "2017 ~ 2018",
    resume: true,
    resumeAccomplishments: [1, 2],
    hasBlackLogo: false,
  },
  {
    key: "hotmart-1",
    companyId: "hotmart",
    companyName: "Hotmart",
    year: "2016 ~ 2017",
    resume: false,
    resumeAccomplishments: [],
    hasBlackLogo: false,
  },
  {
    key: "sydle-2",
    companyId: "sydle",
    companyName: "Sydle",
    year: "2014 ~ 2016",
    resume: false,
    resumeAccomplishments: [],
    hasBlackLogo: true,
  },
  {
    key: "sydle-1",
    companyId: "sydle",
    companyName: "Sydle",
    year: "2012 ~ 2014",
    resume: false,
    resumeAccomplishments: [],
    hasBlackLogo: true,
  },
] as const;
