export type skillType = {
  name: string;
  size: 1 | 2 | 3 | 4 | 5;
};

export const hardSkills: skillType[] = [
  /* Front-End */
  { name: "HTML", size: 5 },
  { name: "CSS", size: 5 },
  { name: "JavaScript", size: 5 },
  { name: "React", size: 4 },
  { name: "Next.js", size: 3 },
  { name: "Tailwind", size: 4 },
  { name: "Vue.js", size: 1 },
  { name: "Nuxt.js", size: 1 },
  { name: "Angular", size: 1 },
  { name: "Responsive Design", size: 4 },
  { name: "SEO", size: 3 },
  { name: "SSR", size: 2 },
  { name: "Sass", size: 4 },
  { name: "Semantical HTML", size: 4 },
  { name: "TypeScript", size: 4 },
  { name: "Webpack", size: 1 },
  { name: "Redux", size: 1 },
  { name: "jQuery", size: 1 },
  { name: "Web Accessibility", size: 3 },
  { name: "Core Web Vitals", size: 4 },
  { name: "Web Performance", size: 2 },
  { name: "Web Security", size: 2 },
  { name: "Web Sockets", size: 1 },
  { name: "Styled Components", size: 1 },
  { name: "PWA", size: 2 },
  /* Back-End */
  { name: "Node.js", size: 3 },
  { name: "Express", size: 3 },
  { name: "LoopBack", size: 1 },
  { name: "Meteor", size: 1 },
  /* Test  */
  { name: "Jest", size: 3 },
  { name: "Code Coverage", size: 3 },
  { name: "React Testing Library", size: 3 },
  { name: "Cypress", size: 2 },
  { name: "Chromatic", size: 1 },
  /* APIs */
  { name: "HTTP", size: 3 },
  { name: "GraphQL", size: 1 },
  { name: "REST", size: 1 },
  /* PHP */
  { name: "PHP", size: 1 },
  { name: "WordPress", size: 1 },
  { name: "Magento", size: 1 },
  { name: "Laravel", size: 1 },
  /* Web Servers */
  { name: "Nginx", size: 3 },
  { name: "Apache", size: 2 },
  /* CI / CD */
  { name: "GitHub Actions", size: 2 },
  { name: "Bash", size: 1 },
  { name: "Docker", size: 1 },
  { name: "YML", size: 1 },
  { name: "AWS", size: 2 },
  { name: "Kubernets", size: 1 },
  { name: "Terraform", size: 1 },
  /* Database */
  { name: "SQL", size: 3 },
  { name: "MySQL", size: 1 },
  { name: "SQL Server", size: 1 },
  { name: "PostgreSQL", size: 1 },
  { name: "Oracle", size: 1 },
  { name: "NoSQL", size: 2 },
  { name: "MongoDB", size: 1 },
  /* Management Tools */
  { name: "Jira", size: 1 },
  { name: "Confluence", size: 1 },
  { name: "Slack Workflows", size: 1 },
  { name: "Slack Apps", size: 1 },
  { name: "BPMN", size: 1 },
  /* Business */
  { name: "A/B Testing", size: 1 },
  { name: "Atomic Design", size: 1 },
  { name: "Design Systems", size: 1 },
  { name: "Semantic Versioning", size: 1 },
  { name: "UI/UX", size: 1 },
  /* Other */
  { name: "Functional Programming", size: 1 },
  { name: "OOP", size: 1 },
  { name: "Regular Expressions", size: 2 },
  { name: "MarkDown", size: 1 },
];

export const softSkills: skillType[] = [
  { name: "Communication", size: 5 },
  { name: "Leadership", size: 5 },
  { name: "Problem Solving", size: 5 },
  { name: "Decision Making", size: 5 },
  { name: "Empathy", size: 5 },
  { name: "Conflict Resolution", size: 4 },
  { name: "Adaptability", size: 4 },
  { name: "Time Management", size: 3 },
  { name: "Organization", size: 3 },
  { name: "Strategic Thinking", size: 3 },
  { name: "Mentoring", size: 4 },
  { name: "Negotiation", size: 4 },
  { name: "Resilience", size: 5 },
  { name: "Critical Thinking", size: 3 },
  { name: "Creativity", size: 3 },
  { name: "Active Listening", size: 3 },
  { name: "Team Building", size: 2 },
  { name: "Cultural Awareness", size: 1 },
  { name: "Ethical Decision Making", size: 1 },
  { name: "Customer Orientation", size: 3 },
  { name: "Learning Agility", size: 3 },
  { name: "Curiosity", size: 4 },
  { name: "Patience", size: 1 },
  { name: "Public Speaking", size: 1 },
  { name: "Networking", size: 1 },
  { name: "Salesmanship", size: 1 },
  { name: "Multitasking", size: 1 },
  { name: "Attention to Detail", size: 1 },
  { name: "Motivation", size: 1 },
  { name: "Persuasion", size: 1 },
  { name: "Emotional Intelligence", size: 1 },
];
