name: Code

on: [push]

jobs:
  dependencies:
    uses: ./.github/workflows/dependencies.yml

  lint:
    name: Lint
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        run: yarn lint

  typescript:
    name: TypeScript
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - name: TypeScript
        run: tsc
