name: Code

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - id: dependencies
        uses: ./.github/actions/dependencies.yml

      - name: Lint
        run: yarn lint

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - id: dependencies
        uses: ./.github/actions/dependencies.yml

      - name: TypeScript
        run: tsc
