name: Code

on: [push]

jobs:
  dependencies:
    name: Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version: 20

      - name: Install dependencies
        run: yarn

      - uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules

  lint:
    name: Lint
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules

      - name: Lint
        run: yarn lint

  typescript:
    name: TypeScript
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: .next/

      - name: TypeScript
        run: tsc
