name: E2E Tests

on: [push]

jobs:
  lint:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version: 20

      - name: Install dependencies
        run: yarn

      - name: Build
        env:
          CYPRESS: true
        run: yarn build

      - name: E2E Tests
        run: |
          yarn start & npx wait-on http://localhost:3000
          yarn cy:run
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-visual-testing
          path: cypress/visual-testing
