name: Tests

on: [push]

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - id: dependencies
        uses: ./.github/actions/dependencies

      - name: Unit Tests
        run: yarn test

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - id: dependencies
        uses: ./.github/actions/dependencies

      - name: Build
        uses: ./.github/workflows/dependencies.yml

      - name: Build
        env:
          CYPRESS: true
        run: yarn build

      - name: E2E Tests
        run: |
          yarn start & npx wait-on http://localhost:3000
          yarn cy:run
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-visual-testing
          path: cypress/visual-testing
